### ISSUE TITLE
Caching Bug

### ISSUE THREAD

**Issue by fatality** [ratepay/magento1.7-module#2]
Hi there,

i encountered a very big problem within your extension. Introduced with commit c9c9661f9fe0ec34ce60f1bd0e528ecd99bbece1 "relocate device fingerprint".

You are trying to cache the whole block "before_body_end" (https://github.com/ratepay/magento1.7-module/commit/c9c9661f9fe0ec34ce60f1bd0e528ecd99bbece1#diff-d09069a4a01a21b624b285cf3a8452be), which has unexpected results, e.g. scripts within this block won't get loaded. This can only be happen if you have parallel requests.

We encountered this in combination with amazon pay (Extension for Amazon Pay will not be working).

So, why you cache the hole block, and not just your "device_ident" block?

Regards,
Marc Rochow

**Comment by schmittrigger** [comment]
Hi Marc,

thanks for the hint!
You're right, caching the whole block isn't the best way to do this. We will change this within the next release (which is planed for begin of June).

Cheers
Aarne
