### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by c-schwan** [ratepay/magento1.7-module#3]
RatePAY_Ratepaypayment_Model_Method_RateAbstract

should be:

` Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_total_amount') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_amount') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_interest_rate') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_interest_amount') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_service_charge') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_annual_percentage_rate') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_monthly_debit_interest') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_number_of_rates_full') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_number_of_rates') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_rate') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
        Mage::getSingleton('ratepaypayment/session')->getData($this->getCode().'_last_rate') == null ? Mage::throwException($this->_getHelper()->__('Berechnen Sie Ihre Raten!')) : "";
`

**Comment by neumann-rp** [comment]
Thanks for your suggestion. 
Where will be the benefit if we are using this solution? All these values are set and stored by us in our custom session array and belong to just one payment method. 
Should your way prevent conflicts? Could you justify why we should do it like you suggested?

**Comment by christian-schwan** [comment]
RatePAY_Ratepaypayment_Model_Method_Rate0 extends RatePAY_Ratepaypayment_Model_Method_RateAbstract

the values that are stored in the session are:

ratepay_rate0_total_amount but you are checking getRatepayRateTotalAmount()

the will fail the whole validation

**Comment by neumann-rp** [comment]
Thanks a lot. You are totally right. 
Thats a point we missed while developing the last features. We will fix it soon in an upcoming release.

**Comment by christian-schwan** [comment]
Thx

Von meinem iPhone gesendet
