### ISSUE TITLE
BUG: Constructor of LibraryConnector

### ISSUE THREAD

**Issue by therouv** [ratepay/magento1.7-module#5]
Der Commit 4f38a9ea69427421e6cc492050677c9b242a6b1b hat eine neuen Bug eingeführt: Es war wohlgemeint, den Konstruktoraufruf zu simplifizieren. Jedoch ist es zwingend notwendig, dass der zweite Parameter von Mage::getSingleton() ein Array ist.

Dieser Bug führt dazu, dass Kunden den Bezahlvorgang nicht abschließen können. Sie werden immer ohne Fehlermeldung zum Warenkorb weitergeleitet.

----

Commit 4f38a9ea69427421e6cc492050677c9b242a6b1b introduced a new bug: Even though it was well intended to simplify the constructor calls, it is mandatory that the second parameter of Mage::getSingleton() is an array. 

This bug leads to customers not being able to complete the checkout process. They always will be redirected to the cart because of this error.

**Comment by rpWhittington** [comment]
Hallo Rouven, 

danke für den Hinweis! 
Wir haben dieses Problem gefunden und bereiten ein Release mit einem Fix vor.  Dies soll Montag geschehen.

Viele Grüße,

Aaron
