### ISSUE TITLE
Erroneous single quote in template?

### ISSUE THREAD

**Issue by Songworks** [ratepay/magento1.7-module#6]
In the template file `app/design/adminhtml/default/default/template/ratepay/payment/form/rate.phtml` line *327:88* there seems to be a single quote after the echo of `$_code` without a corresponding partner:
```js
var customer_dob = new Varien.RatepayDOB(".ratepaydob_<?php echo $_code ?>"', true, '%d.%m.%y');
```
Should it be there or is it in error?
It tripped up my editors syntax highlightning.

Cheers!

**Comment by eiriarte-mendez** [comment]
Hi @Songworks ,
thanks for your advice, I think you're right and that quote is not needed.
We will repair this file as soon as possible.
Cheers
Eduardo

**Comment by MartinKuhl** [comment]
issue resolved in Sep 12, 2019
